name: Build Android Only

on: 
  workflow_dispatch:

jobs:
  buildAndroid:
    name: Build for Android
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - uses: game-ci/unity-builder@v4
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          unityVersion: 6000.0.48f1
          allow-prerelease: true
          targetPlatform: Android

      - uses: actions/upload-artifact@v4
        with:
          name: Build-Android
          path: build/Android
